# Generated by Django 3.2.5 on 2021-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('desciption', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('distrit', models.IntegerField(blank=True, null=True)),
                ('cash', models.BooleanField(blank=True, null=True)),
                ('credit', models.BooleanField(blank=True, null=True)),
                ('transfer', models.BooleanField(blank=True, null=True)),
                ('court_owner', models.IntegerField(blank=True, null=True)),
                ('from_noon', models.TimeField(blank=True, null=True)),
                ('to_noon', models.TimeField(blank=True, null=True)),
                ('from_afternoon', models.TimeField(blank=True, null=True)),
                ('to_afternoon', models.TimeField(blank=True, null=True)),
                ('hour_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
